# Generated by Django 5.2.6 on 2025-10-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_category_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorys',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categorys',
        ),
    ]
