# Generated by Django 5.2.6 on 2025-10-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_category_categorys_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categorys',
            new_name='category',
        ),
    ]
