# Generated by Django 5.2.6 on 2025-12-04 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_payment_method_savedcard_payment_method_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedcard',
            old_name='payment_method_id',
            new_name='payment_method',
        ),
        migrations.RemoveField(
            model_name='savedcard',
            name='created_at',
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
